# Generated by Django 4.2.5 on 2023-09-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_amenity_facility_houserule_remove_room_room_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Aminities"},
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "Facilites"},
        ),
        migrations.AlterModelOptions(
            name="houserule",
            options={"verbose_name_plural": "House Rules"},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={"verbose_name_plural": "Room Types"},
        ),
        migrations.AlterField(
            model_name="room",
            name="beds",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("caption", models.CharField(max_length=80)),
                ("file", models.ImageField(upload_to="")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
