# Generated by Django 4.2.5 on 2023-09-21 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_alter_amenity_options_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="bath",
            new_name="baths",
        ),
    ]
