# Generated by Django 4.2.5 on 2023-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_alter_photo_file"),
        ("lists", "0002_alter_list_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="lists", to="rooms.room"
            ),
        ),
    ]
